#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	patch -Np1 -i ../$name-backspace-1.patch

	sed -i 's/\(RESIZECONS_PROGS=\)yes/\1no/g' configure
	sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

	./configure --prefix=/usr --disable-vlock --disable-nls
	make
	make DESTDIR=$PKG install

	mkdir -p $PKG/bin
	mv -v $PKG/usr/bin/dumpkeys \
	      $PKG/usr/bin/kbd_mode \
	      $PKG/usr/bin/loadkeys \
	      $PKG/usr/bin/setfont \
	      $PKG/bin
}
