#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	export FORCE_UNSAFE_CONFIGURE=1

	./configure \
		--prefix=/usr \
		--libexecdir=/usr/lib \
		--enable-no-install-program=kill,uptime \
		--disable-nls
	make
	make DESTDIR=$PKG install

	mkdir -pv $PKG/bin \
	          $PKG/usr/sbin

	for i in cat chgrp chmod chown cp date dd df echo \
		false ln ls mkdir mknod mv pwd rm rmdir \
		stty sync true uname head sleep nice; do
		mv -v $PKG/usr/bin/$i $PKG/bin
	done

	mv -v $PKG/usr/bin/chroot $PKG/usr/sbin
	mkdir -pv $PKG/usr/share/man/man8
	mv -v $PKG/usr/share/man/man1/chroot.1 $PKG/usr/share/man/man8/chroot.8
	sed -i s/\"1\"/\"8\"/1 $PKG/usr/share/man/man8/chroot.8

}
