#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection
. ./uports-config && PATH=$tpath

pkgname=utoolscross-gmp
pkgver=6.0.0
pkgrel=1
maintainer="linuxchrist@gmail.com"
description="library for arithmetic on arbitrary precision integers,"
homepage="https://www.gnu.org/software/gmp/"
sources="http://ftp.gnu.org/gnu/gmp/gmp-6.0.0a.tar.xz"
arch=amd64
depends=
comment="uports: a universal linux/gnu ports collection"
checkpkginfo

cd $src
if [ ! -f gmp-6.0.0a.tar.xz ]; then wget $sources; fi
tar -xvf gmp-6.0.0a.tar.xz
cd gmp-$pkgver

./configure		\
	--prefix=$utoolscross \
	--enable-cxx    \
	--enable-shared	\
	--enable-static

make -j$(nproc)
make install DESTDIR=$installdir || exit $?

defaultpackager
cd $src && rm -rf gmp-$pkgver
cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
