#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection
. ./uports-config && PATH=$tpath

pkgname=utoolscross-mpfr
pkgver=4.2.1
pkgrel=1
maintainer="linuxchrist@gmail.com"
description="C library for multiple-precision floating-point computations with correct rounding."
homepage="https://www.mpfr.org/"
sources="https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz"
arch=amd64
depends=
comment="uports: a universal linux/gnu ports collection"
checkpkginfo

cd $src
if [ ! -f mpfr-4.2.1.tar.xz ]; then wget $sources; fi
tar -xvf mpfr-4.2.1.tar.xz
cd mpfr-$pkgver

./configure --build=$build        \
	    --host=$build         \
	    --prefix=$utoolscross \
	    --with-gmp=$utoolscross \
	    --enable-shared       \
	    --enable-static

make -j$(nproc)
make install DESTDIR=$installdir || exit $?

defaultpackager
cd $src && rm -rf mpfr-$pkgver
cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
