#!/usr/bin/env bash
#
# initial temporary gcc build
#
# gcc 1st phaze disable libs
# gcc 2nd phaze not disable libs
# gcc 3rd phase enable libs
# uports: a universal linux/gnu ports collection
. ./uports-config && PATH=$tpath

pkgname=utoolscross-gcc
pkgver=4.8.5
pkgrel=1
maintainer="linuxchrist@gmail.com"
description="contains the GNU compiler collection, which includes the C and C++ compilers."
homepage="https://gcc.gnu.org/"
sources="https://ftp.gnu.org/gnu/gcc/gcc-4.8.5/gcc-4.8.5.tar.gz"
arch=amd64
depends=
comment="uports: a universal linux/gnu ports collection"
checkpkginfo

cd $src
if [ ! -f gcc-4.8.5.tar.gz ]; then wget $sources; fi
tar -xvf gcc-4.8.5.tar.gz
cd gcc-$pkgver

#--------------------------------------------------------------------------------------------------------
case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
 ;;
esac
# change GCC's default dynamic linker to use the one installed in /tools.
sed -i 's,/lib/ld-linux.so.2,/utools/lib32/ld-linux.so.2,g' gcc/config/i386/linux64.h
sed -i 's,/lib64/ld-linux-x86-64.so.2,/utools/lib/ld-linux-x86-64.so.2,g' gcc/config/i386/linux64.h
sed -i 's,/libx32/ld-linux-x32.so.2,/utools/libx32/ld-linux-x32.so.2,g' gcc/config/i386/linux64.h

echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/utools/lib/"\n' >> gcc/config/i386/linux64.h
#--------------------------------------------------------------------------------------------------------
mkdir ../gccbuild && cd ../gccbuild
#CFLAGS+="-std=c11" \
CXXFLAGS+="-std=c++14" \
AR=ar LDFLAGS="-Wl,-rpath,/utoolscross/lib" \
../gcc-$pkgver/configure		\
	--prefix=$utoolscross		\
	--build=$build			\
	--host=$build			\
	--target=$crosstarget		\
	--with-sysroot=$ulinux		\
	--with-local-prefix=/utools	\
	--with-native-system-header-dir=/utools/include \
	--disable-nls			\
	--with-mpfr=$utoolscross	\
	--with-gmp=$utoolscross		\
	--with-cloog=$utoolscross	\
	--with-mpc=$utoolscross		\
	--with-isl=$utoolscross		\
	--with-newlib			\
	--without-headers		\
	--disable-libatomic		\
        --disable-libgomp		\
        --disable-libmudflap		\
        --disable-libitm		\
        --disable-libmpx		\
        --disable-libssp		\
        --disable-libvtv		\
        --disable-libquadmath		\
        --disable-libstdcxx		\
        --disable-libstdc++		\
        --disable-libsanitizer		\
        --disable-decimal-float		\
	--enable-libiberty		\
	--with-system-zlib		\
	--enable-static			\
	--disable-shared		\
	--disable-threads		\
	--disable-multilib		\
	--enable-languages=c		\
	--enable-checking=release

make -j$(nproc) all-gcc all-target-libgcc
make install DESTDIR=$installdir install-gcc install-target-libgcc || exit $?

defaultpackager
cd $src && rm -rf gcc-$pkgver gccbuild
cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
