#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection
. ./uports-config && PATH=$tpath

# create a symlink so we can enable shared for next compile or gcc core pass 2
ln -vs libgcc.a `${crosstarget}-gcc -m64 -print-libgcc-file-name | \
    sed 's/libgcc/&_eh/'`
ln -vs libgcc.a `${crosstarget}-gcc -m32 -print-libgcc-file-name | \
    sed 's/libgcc/&_eh/'`
ln -vs libgcc.a `${crosstarget}-gcc -mx32 -print-libgcc-file-name | \
    sed 's/libgcc/&_eh/'`

ln -sv libgcc.a $installdir/utoolscross/lib/gcc/x86_64-cross-linux-gnu/13.2.0/libgcc_eh.a
ln -sv libgcc.a $installdir/utoolscross/lib/gcc/x86_64-cross-linux-gnu/13.2.0/32/libgcc_eh.a
ln -sv libgcc.a $installdir/utoolscross/lib/gcc/x86_64-cross-linux-gnu/13.2.0/x32/libgcc_eh.a

# end of file
