#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	./configure --prefix=/usr                     \
	            --enable-unicode-properties       \
	            --enable-pcre16                   \
	            --enable-pcre32                   \
	            --enable-pcregrep-libz            \
	            --enable-pcregrep-libbz2          \
	            --enable-pcretest-libreadline     \
	            --disable-static
	make
	make DESTDIR=$PKG install

	install -d $PKG/lib
	mv -v $PKG/usr/lib/libpcre.so.* $PKG/lib
	ln -sfv ../../lib/$(readlink $PKG/usr/lib/libpcre.so) $PKG/usr/lib/libpcre.so

}
