#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	./configure --prefix=/usr
	make
	make DESTDIR=$PKG install

	mkdir -p $PKG/lib
	mv -v $PKG/usr/lib/libz.so.* $PKG/lib
	ln -sfv ../../lib/$(readlink $PKG/usr/lib/libz.so) $PKG/usr/lib/libz.so
}
