#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-65ef608163d72c16a721eeecf1f9865ed76f7920
	make DESTDIR=$PKG install
	# from now on, modules-load provided by 'init' port, can be used across other inits
	rm -fr $PKG/usr
}
