#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	export CPPFLAGS="$CPPFLAGS \
		-DSQLITE_ENABLE_COLUMN_METADATA=1 \
		-DSQLITE_ENABLE_UNLOCK_NOTIFY \
		-DSQLITE_ENABLE_DBSTAT_VTAB=1 \
		-DSQLITE_ENABLE_FTS3_TOKENIZER=1 \
		-DSQLITE_ENABLE_FTS3_PARENTHESIS \
		-DSQLITE_SECURE_DELETE \
		-DSQLITE_ENABLE_STMTVTAB \
		-DSQLITE_MAX_VARIABLE_NUMBER=250000 \
		-DSQLITE_MAX_EXPR_DEPTH=10000 \
		-DSQLITE_ENABLE_MATH_FUNCTIONS"

	cd $name-autoconf-$_version

  	./configure --prefix=/usr \
		--disable-static \
		--enable-fts3 \
		--enable-fts4 \
		--enable-fts5 
	sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
	make
	make DESTDIR=$PKG install
}
