#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd lib$name-R_$_v/$name

	./buildconf.sh
	./configure --prefix=/usr --disable-static
        make
        make DESTDIR=$PKG install
}
