#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

  	./configure --libexecdir=/lib/dhcpcd \
	            --dbdir=/var/lib/dhcpcd
	make
	make DESTDIR=$PKG install

	# rc service
	install -Dm755 $SRC/rc.network $PKG/etc/rc.d/network
}
