#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
desciption=
homepage=
arch=
depends=

build() {
	cd $name-$version
	./configure --prefix=/usr    \
	            --bindir=/bin    \
	            --disable-static \
		    --disable-nls    \
	            --libexecdir=/usr/lib
	make
	make DESTDIR=$PKG install

	chmod -v 755 $PKG/usr/lib/libacl.so

	mkdir -p $PKG/lib
	mv -v $PKG/usr/lib/libacl.so.* $PKG/lib
	ln -sfv ../../lib/$(readlink $PKG/usr/lib/libacl.so) $PKG/usr/lib/libacl.so

}
