#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	./configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--without-logger
	make
	make DESTDIR=$PKG install

	install -Dm644 syslog.conf $PKG/etc/syslog.conf

	# rc service
	install -Dm755 $SRC/rc.$name $PKG/etc/rc.d/$name

	# runit service
	install -Dm755 $SRC/run $PKG/etc/sv/$name/run
	ln -s /run/runit/supervise.$name $PKG/etc/sv/$name/supervise
}
