#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	FORCE_UNSAFE_CONFIGURE=1  \
	./configure --prefix=/usr \
		    --libexecdir=/usr/lib/$name \
	            --bindir=/bin \
		    --disable-nls
	make
	make DESTDIR=$PKG install

}
