#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	./configure \
		--prefix=/usr \
		--disable-static \
		--disable-nls \
		--disable-java \
		--disable-csharp \
                --without-git \
                --without-emacs \
                --with-included-libxml \
                --with-included-libcroco \
                --with-included-glib
	make
	make DESTDIR=$PKG install

}

