#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	./configure \
		--prefix=/usr \
		--with-curses \
		--enable-readline \
		--without-bash-malloc \
		--with-installed-readline
	make
	make DESTDIR=$PKG install

	mkdir -p $PKG/bin
	mv $PKG/usr/bin/bash $PKG/bin

	install -d $PKG/etc
	install -m644 $SRC/bashrc $PKG/etc
	install -m644 $SRC/profile $PKG/etc
}
