#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd gmp-$version

	./configure --prefix=/usr \
	            --enable-cxx \
	            --build=${XHOST:-x86_64-unknown-linux-gnu} \
	            --disable-static
	make
	make DESTDIR=$PKG install

}
