#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	make prefix=/usr DESTDIR=$PKG install

	# ship with tzdata
	rm $PKG/usr/share/man/man5/tzfile.5 \
	   $PKG/usr/share/man/man8/zic.8 \
	   $PKG/usr/share/man/man8/tzselect.8 \
	   $PKG/usr/share/man/man8/zdump.8
}
