#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	./configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--with-pkg-config-dir="/usr/lib/pkgconfig:/usr/share/pkgconfig" \
		--with-system-libdir="/lib:/usr/lib" \
		--with-system-includedir="/usr/include"
	make
	make DESTDIR=$PKG install

	ln -sf pkgconf "$PKG"/usr/bin/pkg-config

}
