#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	scratch isinstalled libxslt && _opt="--enable-manpages"

	# remove an unneeded group 'sgx'
	sed -i -e 's/GROUP="sgx", //' rules/50-udev-default.rules

	autoreconf -f -i -s
	./configure \
		--prefix=/usr \
		--bindir=/sbin \
		--sbindir=/sbin \
		--libdir=/usr/lib \
		--sysconfdir=/etc \
		--libexecdir=/lib \
		--with-rootprefix= \
		--with-rootlibdir=/lib \
		--disable-static \
		$_opt
	make

	mkdir -pv $PKG/lib/udev/rules.d
	mkdir -pv $PKG/etc/udev/rules.d

	make DESTDIR=$PKG install
}
