#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd mpfr-$version

	./configure --prefix=/usr        \
	            --disable-static     \
	            --enable-thread-safe
	make
	make DESTDIR=$PKG install

	rm -r $PKG/usr/share
}
