#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends="filesystem linux-api-headers glibc binutils gcc libtool man-pages tzdata zlib file readline m4 libgmp \
libmpfr libmpc  bzip2 pkgconf ncurses attr acl libcap sed shadow psmisc \
iana-etc bison flex grep bash dash which  gdbm gperf expat inetutils perl \
autoconf automake xz kmod gettext elfutils procps-ng e2fsprogs coreutils \
diffutils gawk findutils groff less gzip iproute2 kbd libpipeline make patch \
eudev util-linux man-db tar texinfo vim scratchpkg dhcpcd sysklogd init"

build() {
	mkdir -pv $PKG/usr
}
