#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version
	
	./configure \
		--prefix=/usr \
		--disable-bsdcat \
		--without-lz4 \
		--without-zstd \
		--without-lzma \
		--without-nettle \
		--without-xml2 \
		--disable-static
	make
	make DESTDIR=$PKG install

	# Remove iconv from pc file
	sed -i "s/iconv//" "$PKG/usr/lib/pkgconfig/libarchive.pc"

}
