#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	./config \
		--prefix=/usr \
		--libdir=lib \
		--openssldir=/etc/ssl \
		enable-ec_nistp_64_gcc_128 \
		enable-camellia \
		enable-seed \
		enable-rfc3779 \
		no-mdc2 \
		no-ec2m \
		no-sm2 \
		no-sm4 \
		shared \
		threads \
		zlib

	sed -i "s|-O3|$CFLAGS|" Makefile

	make depend
	make
	make MANSUFFIX=ssl DESTDIR=$PKG install_sw install_ssldirs install_man_docs

	find $PKG -name "*fips*" -delete
}
