#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
desciption=
homepage=
arch=
depends=

build() {
	cd $name-$version

	./configure --prefix=/usr
	make
	make DESTDIR=$PKG install

	rm $PKG/usr/share/automake-*/texinfo.tex
}
