#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	./configure \
		--prefix=/usr \
		--libexecdir=/usr/sbin \
		--localstatedir=/var \
		--disable-logger \
		--disable-whois \
		--disable-rcp \
		--disable-rexec \
		--disable-rlogin \
		--disable-rsh \
		--disable-servers
	make
	make DESTDIR=$PKG install

	mkdir -pv $PKG/bin $PKG/sbin
	mv -v $PKG/usr/bin/hostname \
	      $PKG/usr/bin/ping \
	      $PKG/usr/bin/ping6 \
	      $PKG/usr/bin/traceroute \
	      $PKG/bin
	mv -v $PKG/usr/bin/ifconfig $PKG/sbin

}
