#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	make -C src
	make -C src ROOT=$PKG install

	# remove binaries
	for xx in last lastb readbootlog mesg utmpdump wall; do
		rm $PKG/usr/bin/$xx
	done
	
	rm $PKG/bin/pidof
	rm $PKG/sbin/sulogin
	rm $PKG/sbin/logsave
	
	# remove man
	for xx in last lastb readbootlog mesg utmpdump wall; do
		rm $PKG/usr/share/man/man1/$xx.1
	done
	
	for xx in pidof logsave sulogin; do
		rm $PKG/usr/share/man/man8/$xx.8
	done
}
