#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd linux-$version

	make mrproper
	make headers
	find usr/include -name '.*' -delete
	rm usr/include/Makefile
	mkdir -p $PKG/usr/include
	cp -rv usr/include/* $PKG/usr/include
}
