#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	./configure --prefix=/usr --disable-nls
	make
	make DESTDIR=$PKG install

	mkdir -p $PKG/bin
	mv -v $PKG/usr/bin/fuser   $PKG/bin
	mv -v $PKG/usr/bin/killall $PKG/bin
}
