#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	patch -Np1 -i $SRC/${name}-${version}-upstream_fix-1.patch

	sed -i '/MV.*old/d' Makefile.in
	sed -i '/{OLDSUFF}/c:' support/shlib-install

	./configure \
		--prefix=/usr \
		--disable-static \
		--with-curses
	make SHLIB_LIBS="-lncursesw"
	make SHLIB_LIBS="-lncursesw" DESTDIR=$PKG install

	install -d $PKG/lib
	mv -v $PKG/usr/lib/libreadline.so.* \
	      $PKG/usr/lib/libhistory.so.* \
	      $PKG/lib
	ln -sfv ../../lib/$(readlink $PKG/usr/lib/libreadline.so) $PKG/usr/lib/libreadline.so
	ln -sfv ../../lib/$(readlink $PKG/usr/lib/libhistory.so ) $PKG/usr/lib/libhistory.so

	install -d $PKG/etc
	install -m644 $SRC/inputrc $PKG/etc/inputrc
}
