#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	# fix an issue building the package with Glibc-2.34 or later
	sed -e 's/__attribute_nonnull__/__nonnull/' \
	    -i gnulib/lib/malloc/dynarray-skeleton.c

	./configure --prefix=/usr --disable-static
	make
	make DESTDIR=$PKG install

}
