#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	sed -i '/LIBTOOL_INSTALL/d' c++/Makefile.in

	./configure --prefix=/usr \
	            --mandir=/usr/share/man \
		    --with-pkg-config-libdir=/usr/lib/pkgconfig \
	            --with-shared \
	            --without-debug \
	            --without-normal \
	            --enable-pc-files \
	            --enable-widec
	make
	make DESTDIR=$PKG install

	mkdir -p $PKG/lib
	mv $PKG/usr/lib/libncursesw.so.* $PKG/lib
	ln -sf ../../lib/libncursesw.so.$version $PKG/usr/lib/libncursesw.so
	ln -s libncursesw.so.$version $PKG/lib/libncurses.so.${version%%.*}

	# Create libtinfo symlinks.
	ln -sfr $PKG/usr/lib/libncursesw.so \
		$PKG/usr/lib/libtinfo.so
	ln -sfr $PKG/lib/libncursesw.so.${version} \
		$PKG/usr/lib/libtinfo.so.${version}
	ln -sfr $PKG/usr/lib/libtinfo.so.${version} \
		$PKG/usr/lib/libtinfo.so.6
	ln -sfr $PKG/usr/lib/pkgconfig/ncursesw.pc \
		$PKG/usr/lib/pkgconfig/tinfo.pc
	for lib in ncurses form panel menu ; do
	    rm -vf                    $PKG/usr/lib/lib${lib}.so
	    echo "INPUT(-l${lib}w)" > $PKG/usr/lib/lib${lib}.so
	    ln -sfv ${lib}w.pc        $PKG/usr/lib/pkgconfig/${lib}.pc
	done

	rm -vf                     $PKG/usr/lib/libcursesw.so
	echo "INPUT(-lncursesw)" > $PKG/usr/lib/libcursesw.so
	ln -sfv libncurses.so      $PKG/usr/lib/libcurses.so
}
