#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection

pkgname=
pkgver=
pkgrel=
maintainer= <linuxchrist@gmail.com>
description= Meta port for base system
homepage=
arch=
depends=

build() {
	cd $name-$version

	sed -i "/math.h/a #include <malloc.h>" src/flexdef.h

	./configure --prefix=/usr --disable-nls
	make
	make DESTDIR=$PKG install

	ln -sv flex $PKG/usr/bin/lex

}
