#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection
. ./ulinux-config && PATH=$tpath

pkgname=utoolscross-glibc
pkgver=2.38
pkgrel=1
maintainer="linuxchrist@gmail.com"
description="the main C library. 64 bit abi"
homepage="https://www.gnu.org/software/libc/"
sources="https://ftp.gnu.org/gnu/glibc/glibc-2.38.tar.xz"
arch=amd64
depends=
comment="uports: a universal linux/gnu ports collection"
checkpkginfo

cd $src
if [ ! -f glibc-2.38.tar.xz ]; then wget $sources; fi
tar -xvf glibc-2.38.tar.xz
cd glibc-$pkgver

ln -sfv ../lib/ld-linux-x86-64.so.2 $ulinux/lib64
ln -sfv ../lib/ld-linux-x86-64.so.2 $ulinux/lib64/ld-lsb-x86-64.so.3
mkdir build && cd build
echo "rootsbindir=/usr/sbin" > configparms
../configure			\
	--prefix=/usr		\
	--host=$crosstarget	\
	--build=$(../scripts/config.guess) \
	--enable-kernel=4.19	\
	--with-headers=$ulinux/usr/include \
	--disable-nscd		\
	libc_cv_slibdir=/usr/lib

make -j$(nproc)
make install install-headers DESTDIR=$ulinux || exit $?

#defaultpackager
cd $src && rm -rf glibc-$pkgver
#cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
