#!/usr/bin/env bash
#
#
# ulinux: a simple and universal linux distribution...
. ./ulinux-config && PATH=$tpath

pkgname=utoolscross-glibc
pkgver=2.38
pkgrel=1
maintainer="michkochris@gmail.com"
description="the main C library. 64 bit abi"
homepage="https://www.gnu.org/software/libc/"
sources="https://ftp.gnu.org/gnu/glibc/glibc-2.38.tar.xz"
arch=amd64
depends=
comment="ulinux: a simple and universal linux distribution..."
checkpkginfo

cd $src
if [ ! -f glibc-2.38.tar.xz ]; then wget $sources; fi
tar -xvf glibc-2.38.tar.xz
cd glibc-$pkgver

mkdir build && cd build
echo "rootsbindir=/usr/sbin" > configparms
../configure			\
	--prefix=/usr		\
	--build=$BUILD		\
	--host=$crosstarget	\
	--enable-kernel=4.19	\
	--with-headers=$utools/usr/include \
	--disable-nscd		\
	libc_cv_slibdir=/usr/lib

make -j$(nproc)
make install install-headers DESTDIR=$utools || exit $?

#defaultpackager
cd $src && rm -rf glibc-$pkgver
#cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
