#!/usr/bin/env bash
#
#
# ulinux: a simple and universal linux distribution...
. ./ulinux-config && PATH=$tpath

pkgname=utoolscross-sed
pkgver=4.9
pkgrel=1
maintainer="michkochris@gmail.com"
description="contains a stream editor."
homepage="https://www.gnu.org/software/sed/"
sources="https://ftp.gnu.org/gnu/sed/sed-4.9.tar.xz"
arch=amd64
depends=
comment="ulinux: a simple and universal linux distribution..."
checkpkginfo

cd $src
if [ ! -f sed-4.9.tar.xz ]; then wget $sources; fi
tar -xvf sed-4.9.tar.xz
cd sed-$pkgver
./configure \
        --prefix=/usr   \
        --build=$BUILD  \
        --host=$crosstarget

make -j$(nproc)
make install DESTDIR=$utools || exit $?

#defaultpackager
cd $src && rm -rf $pkgname-$pkgver
#cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
