#!/usr/bin/env bash
#
#
# ulinux: a simple and universal linux distribution...
. ./ulinux-config && PATH=$tpath

pkgname=utoolscross-grep
pkgver=3.11
pkgrel=1
maintainer="michkochris@gmail.com"
description="contains programs for searching through the contents of files."
homepage="https://www.gnu.org/software/grep/"
sources="https://ftp.gnu.org/gnu/grep/grep-3.11.tar.xz"
arch=amd64
depends=
comment="ulinux: a simple and universal linux distribution..."
checkpkginfo

cd $src
if [ ! -f grep-3.11.tar.xz ]; then wget $sources; fi
tar -xvf grep-3.11.tar.xz
cd grep-$pkgver
./configure \
        --prefix=/usr   \
        --build=$BUILD  \
        --host=$crosstarget

make -j$(nproc)
make install DESTDIR=$utools || exit $?

#defaultpackager
cd $src && rm -rf $pkgname-$pkgver
#cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
