#!/usr/bin/env bash
#
#
# ulinux: a simple and universal linux distribution...
. ./ulinux-config && PATH=$tpath

pkgname=utoolscross-gawk
pkgver=5.3.0
pkgrel=1
maintainer="michkochris@gmail.com"
description="contains programs for manipulating text files."
homepage="https://www.gnu.org/software/gawk/"
sources="https://ftp.gnu.org/gnu/gawk/gawk-5.3.0.tar.xz"
arch=amd64
depends=
comment="ulinux: a simple and universal linux distribution..."
checkpkginfo

cd $src
if [ ! -f gawk-5.3.0.tar.xz ]; then wget $sources; fi
tar -xvf gawk-5.3.0.tar.xz
cd gawk-$pkgver
./configure \
        --prefix=/usr   \
        --build=$BUILD  \
        --host=$crosstarget

make -j$(nproc)
make install DESTDIR=$utools || exit $?

#defaultpackager
cd $src && rm -rf $pkgname-$pkgver
#cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
