#!/usr/bin/env bash
#
#
#
#
#
# ulinux: a simple and universal linux distribution...

rm -rfv /ulinux /utools /utoolscross /mnt/ulinux/
dpkg -r utoolscross-binutils utoolscross-gcc utoolscross-linux-headers utoolscross-glibc utoolscross-libstdcxx
rm -rf /ulinux
# end of file
