#!/usr/bin/env bash
#
#
#
#
#
# ulinux: a simple and universal linux distribution...
. ./ulinux-config && PATH=$tpath

pkgname=
pkgver=
pkgrel=
maintainer="linuxchrist@gmail.com"
description=""
homepage=""
sources=""
arch=amd64
depends=
comment="uports: a universal linux/gnu ports collection"
checkpkginfo

cd $src
if [ ! -f  ]; then wget $sources; fi
tar -xvf 
cd 
mkdir -v  && cd 


make -j$(nproc)
make install DESTDIR=$installdir || exit $?

defaultpackager
cd $src && rm -rf 
cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
