#!/usr/bin/env bash
#
#
# ulinux: a simple and universal linux distribution...
. ./ulinux-config && PATH=$tpath

pkgname=
pkgver=
pkgrel=
maintainer="michkochris@gmail.com"
description=""
homepage=""
sources=""
arch=amd64
depends=
comment="ulinux: a simple and universal linux distribution..."
checkpkginfo

cd $src
if [ ! -f  ]; then wget $sources; fi
tar -xvf 
cd $pkgname-$pkgver


make -j$(nproc)
make install DESTDIR= || exit $?

#defaultpackager
cd $src && rm -rf $pkgname-$pkgver
#cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
