#!/usr/bin/env bash
#
#
# ulinux: a simple and universal linux distribution...
. ./ulinux-config && PATH=$tpath

echo 'int main(){}' | $crosstarget-gcc -xc -
readelf -l a.out | grep ld-linux
rm -v a.out
# end of file
